version: '3'
services:
  sf-head-web:
    depends_on:
      - db
    image: node:18-alpine
    restart: always
    volumes:
      - ./projects/sf-head-web:/usr/src/sf-head-web
    working_dir: /usr/src/sf-head-web
    command: npm run dev
    env_file: ./.env.dev
    ports:
      - 3001:3001
    environment:
      - PORT=3001
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
volumes:
  sf-head-web:
